server:
  port: 8081
spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      bootstrap-servers: b-2.mafujishiromsmsk.2mkkld.c2.kafka.ap-northeast-1.amazonaws.com:9098
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: CG-P5_1_1week_latest_wakeup
      auto-offset-reset: latest
      enable-auto-commit: false # コミットの自動実行を有効にする
      max-poll-records: 1  # 一度のpollで取得するレコードの最大数を1に設定
    #      auto-commit-interval: 5000 # コミットの間隔（ミリ秒）
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler